import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
    weight: ['400', '500', '700'], // Specify desired weights
    subsets: ['latin'], // Choose the appropriate subset (e.g., 'latin')
    variable: '--font-dm-sans' // Optional: Define a CSS variable for the font family
});

export const metadata: Metadata = {
  title: "Caio Oliveira | FullStack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${dmSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
